package com.onopry.budgetapp.utils

object CONSTANTS {
    const val ADDING_MONEY_FRAGMENT_TAG = "ADDING_MONEY_FRAGMENT_TAG"
    const val ANALYTICS_FRAGMENT_TAG = "ANALYTICS_FRAGMENT_TAG"
    const val BUDGET_ADN_DEBTS_FRAGMENT_TAG = "BUDGET_ADN_DEBTS_FRAGMENT_TAG"
    const val CATEGORY_BOTTOMSHEET_FRAGMENT_TAG = "CATEGORY_BOTTOMSHEET_FRAGMENT_TAG"
    const val MORE_FRAGMENT_TAG = "MORE_FRAGMENT_TAG"
    const val TRANSACTION_FRAGMENT_TAG = "TRANSACTION_FRAGMENT_TAG"
}